# from ui import Ui_MainWindow
# from PySide6 import QtWidgets
# from PySide6.QtWidgets import QApplication, QMainWindow

# class CameraUI(QMainWindow):
#     def __init__(self):
#         super().__init__()
#         self.ui = Ui_MainWindow()
#         self.ui.setupUi(self)

from PySide6 import QtWidgets, QtUiTools
from camera_ui import Ui_MainWindow  # generated by pyuic or loadUi

class CameraUI(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

        # Access QTableWidget using its objectName from Qt Designer
        self.tableWidget.horizontalHeader().setSectionResizeMode(
            QtWidgets.QHeaderView.Stretch
        )
